# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=AppTheme
ComponentsDir=app/src/main/java/cn/binbin/tsra/lumo
PackageName=cn.binbin.tsra.lumo
# Uncomment this line if you are using Kotlin Multiplatform
# KotlinMultiplatform=false 